name: Prod Terraform CI/CD

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: export Flux credentials
        run: |
          export GITHUB_USER=DEV_GITHUB_USER
          export GITHUB_TOKEN=DEV_GITHUB_TOKEN
      - name: Set AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: Run AWS CLI command
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1  # Replace with your desired AWS region #         aws s3api create-bucket --bucket eks-application-state-bucket --region us-east-1
          aws s3 ls  # Example AWS CLI command
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10

      - name: Terraform Validate init Stage
        run: |
          cd modules/prod
          terraform init
      - name: Terraform Plan Stage
        run: |
          pwd
          ls
          cd modules/prod
          terraform plan -lock=false
      - name: Terraform Apply Stage
        run: |
          cd modules/prod
          terraform destroy -auto-approve -lock=false
